grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 5
      - 7
      - 12

  module_2:
    class:  GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      criterion : squared_error
      min_samples_leaf: 2
    search_param_grid:
      criterion:
      - friedman_mse
      min_samples_leaf :
      - 5
      - 7
      - 12